server:
  port: 8090
beetl:
  delimiter-statement-start: \@
  delimiter-statement-end: null
  resource-tagroot: common/tags
  resource-tagsuffix: tag
  resource-auto-check: true
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tempest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    db-name: tempest
    filters: log4j,wall,mergeStat








